# SYNOPSIS
# Detects and reports Windows Update installation errors from system event logs for Intune compliance monitoring.

# DESCRIPTION
# This script scans the Windows System Event Log for specific Windows Update-related Event IDs 
# generated by the Windows Update Client. It identifies failed update installations by extracting 
# error codes and filtering only relevant updates such as Security Updates, Cumulative Updates, 
# and Windows Updates.

# The script excludes non-relevant entries (e.g., Defender updates, drivers, firmware, and vendor-specific updates) 
# to reduce noise and improve accuracy.

# Detected errors are grouped to remove duplicates and summarized with occurrence counts. 
# The final output is formatted for Intune Proactive Remediation, where:
# - Exit code 1 indicates update failures detected (non-compliant)
# - Exit code 0 indicates no issues found (compliant)

# This helps administrators quickly identify recurring Windows Update failures across devices 
# and take corrective actions efficiently.

# DEMO
# YouTube video link → https://www.youtube.com/@chandermanipandey8763

# NOTES
# Version:         V1.0  
# Author:          Chander Mani Pandey 
# Creation Date:   24 March 2026

# Find the author on: 
 
# YouTube:         https://www.youtube.com/@chandermanipandey8763  
# Twitter:         https://twitter.com/Mani_CMPandey  
# LinkedIn:        https://www.linkedin.com/in/chandermanipandey  
# BlueSky:         https://bsky.app/profile/chandermanipandey.bsky.social
# GitHub:          https://github.com/ChanderManiPandey2022


param(
    [int]$MaxEvents = 10,
    [int[]]$EventIDs = @(20)   # You can pass 20,30 etc.
)

# ================= FILTER =================
$filter = @{
    LogName      = 'System'
    Id           = $EventIDs
    ProviderName = 'Microsoft-Windows-WindowsUpdateClient'
}

# Exclusion pattern (optimized)
$excludePattern = 'Defender Antivirus|Security Intelligence|Windows Malicious Software Removal Tool|-Microsoft\.|MicrosoftWindows\.|Store|App|AppRuntime|Dell|Intel|HP|Hewlett-Packard|Semiconductor|Firmware|Extension|Driver'

# ================= GET EVENTS =================
$events = Get-WinEvent -FilterHashtable $filter -MaxEvents $MaxEvents -ErrorAction SilentlyContinue

if (-not $events) {
    Write-Output "No matching Event ID(s) found"
    exit 0
}

# ================= PROCESS =================
$results = foreach ($event in $events) {

    $msg = $event.Message

    if ($msg -match 'error\s+(0x[0-9A-Fa-f]+)') {

        if (
            # Include only real Windows updates
            $msg -match 'KB\d+' -and
            $msg -match 'Security Update|Cumulative Update|Update for Windows' -and

            # Exclude unwanted noise
            $msg -notmatch $excludePattern
        ) {
            [PSCustomObject]@{
                Key       = "$($matches[1])|$msg"
                ErrorCode = $matches[1]
                Message   = $msg.Trim()
            }
        }
    }
}

# Remove empty
$results = $results | Where-Object { $_ }

if (-not $results) {
    Write-Output "No Error"
    exit 0
}

# ================= GROUP (NO DUPLICATES) =================
$grouped = $results | Group-Object Key

# ================= OUTPUT (INTUNE FIX) =================
$outputLines = @()

foreach ($group in $grouped) {
    $item  = $group.Group[0]
    $count = $group.Count

    $outputLines += "Error $($item.ErrorCode) ($count Times) : -$($item.Message)"
}

# Print ALL lines (important for Intune)
$outputLines -join "`n" | Write-Output

# ================= EXIT =================
if ($grouped.Count -gt 0) {
    exit 1   # Errors found
} else {
    exit 0
}